Repository MJU-Bonda/BE, pull requests merged in 2025-07, with the labels that each got.

#83 [CHORE] 도서 주제 수정
  src/main/java/bonda/bonda/domain/book/domain/Subject.java
  src/main/resources/db/migration/V2__edit_book_subject.sql
Labels: 🛠️ 리팩토링

#86 v0.0.4 Deploy
  src/main/java/bonda/bonda/domain/book/application/BookCommandServiceImpl.java
  src/main/java/bonda/bonda/domain/book/domain/Subject.java
  src/main/java/bonda/bonda/domain/book/domain/repository/BookRepository.java
  src/main/resources/db/migration/V2__edit_book_subject.sql
Labels: 🔖버전

#88 [FEAT]: 아티클 저장 응답 형식 수정 및, api 하나로 통일
  src/main/java/bonda/bonda/domain/article/application/ArticleCommandService.java
  src/main/java/bonda/bonda/domain/article/application/ArticleCommandServiceImpl.java
  src/main/java/bonda/bonda/domain/article/dto/response/DeleteSaveArticleRes.java
  src/main/java/bonda/bonda/domain/article/dto/response/ToggleBookmarkRes.java
  src/main/java/bonda/bonda/domain/article/presentation/ArticleApi.java
  src/main/java/bonda/bonda/domain/article/presentation/ArticleController.java
  src/main/java/bonda/bonda/domain/articlecase/repository/ArticlecaseRepository.java
  src/main/java/bonda/bonda/domain/book/application/BookSearchService.java
Labels: 🛠️ 리팩토링

#93 v1.0.1 Deploy
  src/main/java/bonda/bonda/domain/article/application/ArticleCommandService.java
  src/main/java/bonda/bonda/domain/article/application/ArticleCommandServiceImpl.java
  src/main/java/bonda/bonda/domain/article/domain/repository/ArticleRepositoryCustomImpl.java
  src/main/java/bonda/bonda/domain/article/dto/response/DeleteSaveArticleRes.java
  src/main/java/bonda/bonda/domain/article/dto/response/ToggleBookmarkRes.java
  src/main/java/bonda/bonda/domain/article/presentation/ArticleApi.java
  src/main/java/bonda/bonda/domain/article/presentation/ArticleController.java
  src/main/java/bonda/bonda/domain/articlecase/repository/ArticlecaseRepository.java
  src/main/java/bonda/bonda/domain/book/application/BookCommandService.java
  src/main/java/bonda/bonda/domain/book/application/BookCommandServiceImpl.java
  src/main/java/bonda/bonda/domain/book/application/BookSearchService.java
  src/main/java/bonda/bonda/domain/book/dto/response/DeleteSaveBookRes.java
  src/main/java/bonda/bonda/domain/book/dto/response/RelatedBookRes.java
  src/main/java/bonda/bonda/domain/book/dto/response/ToggleBookSaveRes.java
  src/main/java/bonda/bonda/domain/book/presentation/BookApi.java
  src/main/java/bonda/bonda/domain/book/presentation/BookController.java
Labels: 🔖버전

#96 v1.0.2 Deploy
  src/main/java/bonda/bonda/domain/auth/presentation/AuthApi.java
  src/main/java/bonda/bonda/domain/auth/presentation/AuthController.java
  src/main/java/bonda/bonda/domain/badge/presentation/BadgeApi.java
  src/main/java/bonda/bonda/domain/member/presentation/MemberApi.java
  src/main/java/bonda/bonda/domain/member/presentation/MemberController.java
  src/main/java/bonda/bonda/domain/searchterm/presentation/SearchTermApi.java
Labels: 🔖버전, :earth_americas: 인프라
