Repository MJU-Bonda/BE, pull requests merged in 2025-05, with the labels that each got.

#3 [FEAT] Entity 세팅
  .gitattributes
  .gitignore
  build.gradle
  src/main/java/bonda/bonda/domain/article/application/ArticleService.java
  src/main/java/bonda/bonda/domain/article/domain/Article.java
  src/main/java/bonda/bonda/domain/article/domain/ArticleCategory.java
  src/main/java/bonda/bonda/domain/article/domain/repository/ArtcleRepository.java
  src/main/java/bonda/bonda/domain/article/presentation/ArticleController.java
  src/main/java/bonda/bonda/domain/articlecase/Articlecase.java
  src/main/java/bonda/bonda/domain/articlecase/repository/ArticlecaseRepository.java
  src/main/java/bonda/bonda/domain/auth/application/AuthService.java
  src/main/java/bonda/bonda/domain/auth/presentation/AuthController.java
  src/main/java/bonda/bonda/domain/badge/application/BadgeService.java
  src/main/java/bonda/bonda/domain/badge/domain/Badge.java
  src/main/java/bonda/bonda/domain/badge/domain/ProgressType.java
  src/main/java/bonda/bonda/domain/badge/domain/repository/BadgeRepository.java
  src/main/java/bonda/bonda/domain/badge/presentation/BadgeController.java
  src/main/java/bonda/bonda/domain/book/application/BookService.java
  src/main/java/bonda/bonda/domain/book/domain/Book.java
  src/main/java/bonda/bonda/domain/book/domain/BookCategory.java
  src/main/java/bonda/bonda/domain/book/domain/Subject.java
  src/main/java/bonda/bonda/domain/book/domain/repository/BookRepository.java
  src/main/java/bonda/bonda/domain/book/presentation/BookController.java
  src/main/java/bonda/bonda/domain/bookarticle/BookArticle.java
  src/main/java/bonda/bonda/domain/bookarticle/repository/BookArticleRepository.java
  src/main/java/bonda/bonda/domain/bookcase/Bookcase.java
  src/main/java/bonda/bonda/domain/bookcase/repository/BookcaseRepository.java
  src/main/java/bonda/bonda/domain/common/BaseEntity.java
  src/main/java/bonda/bonda/domain/member/application/MemberService.java
  src/main/java/bonda/bonda/domain/member/domain/Member.java
  src/main/java/bonda/bonda/domain/member/domain/repository/MemberRepository.java
  src/main/java/bonda/bonda/domain/member/presentation/MemberController.java
  src/main/java/bonda/bonda/domain/memberbadge/MemberBadge.java
  src/main/java/bonda/bonda/domain/memberbadge/repository/MemberBadgeRepository.java
  src/main/java/bonda/bonda/domain/recentviewarticle/RecentViewArticle.java
  src/main/java/bonda/bonda/domain/recentviewarticle/repository/RecentViewArticleRepository.java
  src/main/java/bonda/bonda/domain/recentviewbook/RecentViewBook.java
  src/main/java/bonda/bonda/domain/recentviewbook/repository/RecentViewBookRepository.java
  src/main/java/bonda/bonda/global/common/Message.java
  src/main/java/bonda/bonda/global/common/SuccessResponse.java
  src/main/java/bonda/bonda/global/config/SecurityConfig.java
  src/main/java/bonda/bonda/global/exception/BusinessException.java
  src/main/java/bonda/bonda/global/exception/ErrorCode.java
  src/main/java/bonda/bonda/global/exception/ErrorResponse.java
  src/main/java/bonda/bonda/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V1_Initialize_project_table.sql
  src/main/resources/db/migration/V1__init.sql
Labels: :rainbow: 기능

#7 [FEAT] AWS S3 세팅 및 업로드, 삭제 구현 완료
  .gitignore
  build.gradle
  src/main/java/bonda/bonda/global/common/aws/S3Service.java
  src/main/java/bonda/bonda/global/config/S3Config.java
  src/main/java/bonda/bonda/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: :earth_americas: 인프라

#9 [FEAT] 카테고리별 도서 카드 목록 조회 기능 구현 완료
  src/main/java/bonda/bonda/domain/book/application/BookReadService.java
  src/main/java/bonda/bonda/domain/book/application/BookReadServiceImpl.java
  src/main/java/bonda/bonda/domain/book/application/BookSearchService.java
  src/main/java/bonda/bonda/domain/book/application/BookService.java
  src/main/java/bonda/bonda/domain/book/domain/BookCategory.java
  src/main/java/bonda/bonda/domain/book/domain/Subject.java
  src/main/java/bonda/bonda/domain/book/domain/repository/BookRepository.java
  src/main/java/bonda/bonda/domain/book/domain/repository/BookRepositoryCustom.java
  src/main/java/bonda/bonda/domain/book/domain/repository/BookRepositoryImpl.java
  src/main/java/bonda/bonda/domain/book/dto/response/BookListByCategoryRes.java
  src/main/java/bonda/bonda/domain/book/dto/response/BookListRes.java
  src/main/java/bonda/bonda/domain/book/presentation/BookController.java
  src/main/java/bonda/bonda/global/config/SecurityConfig.java
  src/main/java/bonda/bonda/global/exception/ErrorCode.java
  src/main/java/bonda/bonda/global/exception/GlobalExceptionHandler.java
  src/test/java/bonda/bonda/domain/book/domain/repository/BookQueryDslInitTest.java
Labels: :rainbow: 기능

#16 [FEAT]: 카카오 로그인
  build.gradle
  src/main/java/bonda/bonda/domain/auth/application/AuthService.java
  src/main/java/bonda/bonda/domain/auth/application/KakaoTokenValidator.java
  src/main/java/bonda/bonda/domain/auth/dto/request/LoginReq.java
  src/main/java/bonda/bonda/domain/auth/dto/response/LoginRes.java
  src/main/java/bonda/bonda/domain/auth/presentation/AuthApi.java
  src/main/java/bonda/bonda/domain/auth/presentation/AuthController.java
  src/main/java/bonda/bonda/domain/member/domain/repository/MemberRepository.java
  src/main/java/bonda/bonda/domain/member/dto/response/KakaoMemberRes.java
  src/main/java/bonda/bonda/global/annotation/LoginMember.java
  src/main/java/bonda/bonda/global/config/SecurityConfig.java
  src/main/java/bonda/bonda/global/config/SwaggerConfig.java
  src/main/java/bonda/bonda/global/config/WebMvcConfig.java
  src/main/java/bonda/bonda/global/resolver/LoginMemberArgumentResolver.java
Labels: :rainbow: 기능, :earth_americas: 인프라
